name: Deploy Echo 

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with: 
        path: project/echo-docs
        submodules: true
    - uses: actions/setup-node@v4
      with:
        node-version: '18.x'
    - working-directory: ./project/echo-docs
      run: |
        npm i
        npm run build
        mkdir -p ../../liriliri/echo
        cp -r dist/* ../../liriliri/echo
    - uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        source: "liriliri/echo/"
        target: "/var/www/"